# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Prasanna Asokkumar
description: "Hi I'm Prasanna Asokkumar and I've worked as an Analyst in Consulting in multiple data roles. My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on continuous learning, actionable insights and business impact. Please visit my Github & LinkedIn pages (or download my CV) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
resume_url: /docs/Prasanna_Asokkumar_CV.pdf
avatar_image: /img/Prasanna_Square.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/prasanna-asokkumar/" # Add your linkedln handle
github: "https://github.com/Prasanna-Asokkumar"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


